function test_convergence_ftbs(a, T, hs, lambda)

    uK = @(h,k,K,t,x) ...
         exp(-2*pi^2*K^2*a*(h-a*k)*t) ...
      .* cos(2*pi*K*(x - a*t));
    u = @(h,k,t,x) uK(h,k,1,t,x) - 2*uK(h,k,2,t,x) + 3*uK(h,k,3,t,x);
    test_convergence( ...
        a, T, u, ...
        @ftbs, "forward-time backward-space", ...
        hs, @(h) lambda*h);

endfunction
