function test_convergence_ftbs(a, T, hs, lambda)

    uK = @(k,h,K,t,x) ...
         exp(-2*pi^2*K^2*a*(h-a*k)*t) ...
      .* cos(2*pi*K*(x - a*t));
    u = @(k,h,t,x) uK(k,h,1,t,x) - 2*uK(k,h,2,t,x) + 3*uK(k,h,3,t,x);
    test_convergence( ...
        a, T, u, ...
        @ftbs, "forward-time backward-space", ...
        hs, @(h) lambda*h);

endfunction
