function test_convergence_lax_friedrichs(a, T, hs, lambda)

    uK = @(h,k,K,t,x) ...
         exp(-2*pi^2*K^2*(h^2/k-a^2*k)*t) ...
      .* cos(2*pi*K*(x - a*t));
    u = @(h,k,t,x) uK(h,k,1,t,x) - 2*uK(h,k,2,t,x) + 3*uK(h,k,3,t,x);
    test_convergence( ...
        a, T, u, ...
        @lax_friedrichs, "Lax-Friedrichs", ...
        hs, @(h) lambda*h);

endfunction
