function v = lax_wendroff_btcs(v, a, b, k, h)
    % (1/k)*(v^{n+1}_m - v^n_m) ...
    %     + (a/(2*h))*(v^n_{m+1} - v^n_{m-1}) ...
    %     - (a^2*k/(2*h^2))*(v^n_{m+1} - 2*v^n_m + v^n_{m-1}) ...
    %     - (b/h^2)*(v^{n+1}_{m+1} - 2*v^{n+1}_m + v^{n+1}_{m-1}) = 0
    M = length(v) - 1;
    persistent A = construct_A(b,M,k,h);
    if size(A,1) ~= M || A(1,1) ~= 1 + 2*b*k/h^2
        A = construct_A(b,M,k,h);
    endif
    v = ((1-(a*k/h)^2)*v(1:M) ...
       + (a*k/(2*h))*(a*k/h-1)*v(2:M+1) ...
       + (a*k/(2*h))*(a*k/h+1)*v([M 1:M-1])) / A;
    v(end+1) = v(1);
endfunction

function A = construct_A(b, M, k, h)
    A = spdiags( ...
            repmat([-b*k/h^2 1+2*b*k/h^2 -b*k/h^2], M, 1), ...
            [-1 0 +1], ...
            M, M);
    A(1,M) = -b*k/h^2;
    A(M,1) = -b*k/h^2;
endfunction
