function u = burgers_solution(t,x)
    if t == 0
        u = (x == 1) .* 1 ...
          + (1 < x & x < 2) .* 2 ...
          + (x == 2) .* 1;
    elseif t < 1
        u = (1 < x & x <= 1+2*t) .* ((x-1)/t) ...
          + (1+2*t < x & x < 2+t) .* 2 ...
          + (x == 2+t) .* 1;
    elseif 1+2*sqrt(t) < 4
        u = (1 < x & x < 1+2*sqrt(t)) .* ((x-1)/t) ...
          + (x == 1+2*sqrt(t)) .* (1/sqrt(t));
    elseif t < 4
        u = (0 <= x & x < 2*sqrt(t)-3) .* ((x+3)/t) ...
          + (x == 2*sqrt(t)-3) .* (1/sqrt(t)) ...
          + (1 < x & x <= 4) .* ((x-1)/t);
    else
        x0 = mod(t/2-1,4);
        u = (0 <= x & x < x0) .* (1/2 + (x-x0+2)/t) ...
          + (x == x0) .* (1/2) ...
          + (x0 < x & x <= 4) .* (1/2 + (x-x0-2)/t);
    endif
endfunction
